project:
  type: website
  output-dir: _site
website:
  title: "Measuring Scribal Literacy"
  navbar:
    left:
      - href: gordin_measuring_literacy.qmd
        text: "Presentation"
format:
  revealjs:
    theme: simple
    slide-number: true
    toc: true
